create schema if not exists auth;

create table if not exists auth.users(
    id bigint generated by default as identity primary key ,
    first_name varchar(30) not null ,
    last_name varchar(30) not null ,
    email varchar(50) not null unique ,
    password varchar not null ,
    role varchar not null,
    email_confirmed boolean not null
);

create table if not exists auth.confirmation_codes(
    id bigint generated by default as identity primary key ,
    code int not null ,
    expiration_date timestamp not null ,
    type varchar not null ,
    user_id bigint references auth.users(id) on delete cascade
);

create index on auth.users(email);

create table if not exists auth.refresh_tokens(
    id int generated by default as identity primary key,
    user_id bigint references auth.users(id) on delete cascade,
    token varchar not null,
    expiry_date timestamp not null,
    foreign key(user_id) references auth.users(id) on delete cascade
);



-- Test: UserTests get()
-- Description: Get the user
insert into auth.users(first_name, last_name, email, password, role, email_confirmed) values ('Mike', 'Thompson', 'mike_thompson@gmail.com', 'password123', 'ROLE_USER',false);

-- Test: UserTests update()
-- Description: Update the user
insert into auth.users(first_name, last_name, email, password, role, email_confirmed) values ('Kate', 'Thompson', 'kate_thompson@gmail.com', '123password123', 'ROLE_USER', false);

-- Test: UserTests delete()
-- Description: Delete the user
insert into auth.users(first_name, last_name, email, password, role, email_confirmed) values ('Jake', 'Thompson', 'jake_thompson@gmail.com', '123password123', 'ROLE_USER', false);
