create schema if not exists account;

create table if not exists account.users(
    id bigint generated by default as identity primary key ,
    first_name varchar(30) not null ,
    last_name varchar(30) not null ,
    email varchar(50) not null unique ,
    password varchar not null ,
    role varchar not null,
    email_confirmed boolean not null
);

create index on account.users(email);